import org.jetbrains.intellij.platform.gradle.TestFrameworkType
import org.jetbrains.intellij.platform.gradle.tasks.PrepareSandboxTask
import org.jetbrains.intellij.platform.gradle.Constants.Tasks

plugins {
    id "java"
    id "org.jetbrains.intellij.platform" version "2.10.5"
}

group = "n.v.k"
version = hasProperty("buildVersion") ? buildVersion : "1.0-SNAPSHOT"

repositories {
    mavenCentral()

    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    intellijPlatform {
        bundledPlugin "com.intellij.clion"
        bundledPlugin "com.intellij.modules.cidr.debugger"
        testFramework TestFrameworkType.Platform.INSTANCE
    }
}

def targetIdeVersion = "2025.3.1"
def clionLocalSandbox = System.getenv("QT6RENDERER_SANDBOX_IDE") //C:\Program Files\JetBrains\CLion 2025\

if (clionLocalSandbox) {
    logger.lifecycle "Using sandbox IDE at: ${clionLocalSandbox}"
    dependencies.intellijPlatform.local clionLocalSandbox
} else {
    logger.lifecycle "Using the downloaded IDE: ${targetIdeVersion}"
    dependencies.intellijPlatform.clion targetIdeVersion
}

intellijPlatform {
    buildSearchableOptions = false

    pluginConfiguration {
        id = "n.v.k.Qt6Renderer"
        name = "Qt6 Renderer"
        description = """
        The plugin for pretty printing Qt types by CLion debugger.
        Supported Qt versions: 6.x.
        Supported platforms: Windows, Linux.
        Supported architectures: X64.
        Supported debuggers: GDB, LLDB.
        """.stripIndent()

        changeNotes = """
        * 1.2.0
        - QJson support for LLDB
        - Minor render bug fixes

        * 1.1.1
        - Minor render bug fixes

        * 1.1.0
        - GDB support
        - LLDB code rewritten

        * 1.0.0
        Initial version
        """.stripIndent()

        ideaVersion {
            sinceBuild = "213.6461"
        }

        vendor {
            name = "Nikita Kobzev"
            email = "win.accuracy@gmail.com"
            url = "https://github.com/winseros"
        }
    }
}
def taskNameCopyPrettyPrinters = "copyPrettyPrinters"

tasks.register(taskNameCopyPrettyPrinters, Copy) {
    group = "Qt6Renderer"
    configure {
        def prepareSandboxTask = tasks.named(Tasks.PREPARE_SANDBOX, PrepareSandboxTask)
        def pluginDirectoryProvider = prepareSandboxTask.flatMap { it.pluginDirectory }

        dependsOn Tasks.PREPARE_SANDBOX
        from project.layout.projectDirectory.dir("qt6renderer/python")
        include "**/*.py"
        into project.layout.buildDirectory.dir("${pluginDirectoryProvider.get()}/python").get()
    }
}

tasks.named(Tasks.BUILD_PLUGIN) {
    dependsOn taskNameCopyPrettyPrinters
}

tasks.named(Tasks.RUN_IDE) {
    dependsOn taskNameCopyPrettyPrinters
}
