import org.jetbrains.intellij.platform.gradle.TestFrameworkType
import org.jetbrains.intellij.platform.gradle.tasks.PrepareSandboxTask
import org.jetbrains.intellij.platform.gradle.Constants.Tasks

plugins {
    id "java"
    id "org.jetbrains.intellij.platform" version "2.10.5"
}

group = "n.v.k"
version = hasProperty("buildVersion") ? buildVersion : "1.0-SNAPSHOT"

repositories {
    mavenCentral()

    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    intellijPlatform {
        bundledPlugin "com.intellij.clion"
        bundledPlugin "com.intellij.modules.cidr.debugger"
        testFramework TestFrameworkType.Platform.INSTANCE
    }
}

if (hasProperty("clionLocalSandbox")) {
    logger.lifecycle "Using sandbox IDE at: ${clionLocalSandbox}"
    dependencies.intellijPlatform.local clionLocalSandbox
} else {
    def targetIdeVersion = "2025.3.1"
    logger.lifecycle "Using the downloaded IDE: ${targetIdeVersion}"
    dependencies.intellijPlatform.clion targetIdeVersion
}

intellijPlatform {
    buildSearchableOptions = false

    pluginConfiguration {
        id = "${project.group}.${project.name}"

        description = """<pre>
        The plugin for pretty printing Qt types by CLion debugger.
        
        Supported Qt versions: 6.x.
        Supported platforms: Windows, Linux.
        Supported architectures: X64.
        Supported debuggers: GDB, LLDB.</pre>
        """.stripIndent()

        changeNotes = """
        <ul>
            <li>
                1.2.0
                <ul>
                    <li>QJson support for LLDB</li>
                    <li>Render bug fixes</li>
                </ul>
            </li>
            <li>
                1.1.1
                <ul>
                    <li>Minor render bug fixes</li>
                </ul>
            </li>
            <li>
                1.1.0
                <ul>
                    <li>GDB support</li>
                    <li>LLDB code rewritten</li>
                </ul>
            </li>  
            <li>
                1.0.0
                <ul>
                    <li>Initial version</li>
                </ul>
            </li>
        </ul>
        """.stripIndent()

        ideaVersion {
            sinceBuild = "213.6461"
        }

        vendor {
            name = "Nikita Kobzev"
            email = "win.accuracy@gmail.com"
            url = "https://github.com/winseros"
        }
    }
}

tasks.named(Tasks.PREPARE_SANDBOX, PrepareSandboxTask) {
    from(project.layout.projectDirectory.dir("qt6renderer/python/")) {
        include "**/*.py"
        into pluginName.map { "${it}/python" }
        preserve {
            include "**/*"
        }
    }
}